server:
  port: 443
  ssl:
    key-store: classpath:2889775_13wangluokeji.cn.pfx
    key-store-password: 9Ljw89cm
    key-store-type: PKCS12
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yswl2019
    url: jdbc:mysql://****:3306/db_yswletc?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1200000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #配置redis
  redis:
    host: ****
    port: 6379
#配置图片管理器
fdfs:
  tracker-list:
    - *****:22122
  connect-timeout: 5000
  so-timeout: 5000
  thumb-image:
    height: 300
    width: 300
  pool:
    jmx-enabled: false
#xml映射路径
mybatis-plus:
  mapper-locations: classpath:com/yswl/yswletc/dao/mapper/*.xml
  type-aliases-package: com.yswl.yswletc.entity
#图片服务器路径
img:
  server: http://*****:83/