server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yswl2019
    url: jdbc:mysql://47.92.86.199:3306/db_yswletc?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #配置redis
  redis:
    host: 47.92.86.199
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置图片管理器
fdfs:
  tracker-list:
    - 47.92.86.199:22122
  connect-timeout: 5000
  so-timeout: 5000
  thumb-image:
    height: 300
    width: 300
  pool:
    jmx-enabled: false
#xml映射路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yswl.yswletc.entity
#图片服务器路径
img:
  server: http://47.92.86.199:83/