server:
  port: 443
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ***
    password: ***
    url: jdbc:mysql://****/db_yswletc?serverTimezone=UTC&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-DD HH:MM:SS
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#配置redis
  redis:
    host: ****
    port: 6379
#配置图片管理器
fdfs:
  tracker-list:
    - ****:22122
  connect-timeout: 5000
  so-timeout: 5000
  thumb-image:
    height: 300
    width: 300
  pool:
    jmx-enabled: false
#xml映射路径
mybatis-plus:
  mapper-locations: classpath:com/yswl/yswletc/dao/mapper/*.xml
#图片服务器路径
img:
  server: http://****/